config/routes.rb
Rails.application.routes.draw do
  resources :hoods
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :places

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/about'  => 'page#about'
  get '/contact' => 'page#contact'
  get '/listings' => 'page#listings'
  get '/hoods' => 'page#hoods'


  root :to => "page#home"
end

app/models/ImageUploader.rb
#

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    if user.admin_role?
          can :manage, :all
          can :access, :rails_admin       # only allow admin users to access Rails Admin
          can :dashboard                  # allow access to dashboard
    end
    # if user.supervisor_role?
    #       can :manage, User
    # end
    # Wait on this...
    # if user.agent_role?
    #   can :manage, User
    # end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hood.rb
class ImageUploader < Shrine
  # plugins and uploading logic
end

class Hood < ApplicationRecord
  include ImageUploader[:image]
  extend FriendlyId
  friendly_id :name, use: :slugged
  # alias_attribute :slug, :name

end

app/models/place.rb
# this is some  serious hoe shit, fix this

class ImageUploader < Shrine
  # plugins and uploading logic
end


class Place < ApplicationRecord
  # include ImageUploader::Attachment.new(:image) # adds an `image` virtual attribute
  include ImageUploader[:image]
  extend FriendlyId
  friendly_id :address, use: :slugged

def title_address
  r = self.address + ", " + self.city # + ", " + self.zip
  r.upcase
end

  def image_url
    if self.image?
      self.image.url
    else
      "/public/no-image.png"
    end
  end

  def sale_or_lease?
    case
    when self.saleOrLease == "s"
      return "sale"
    when self.saleOrLease == "l"
      return "lease"
    else
      return "sale"
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    # app_dashboard_index_path # this will be where our dashboard go
    root_path
  end

end

app/controllers/hoods_controller.rb
class HoodsController < ApplicationController
  before_action :set_hood, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, :only => [:index, :show]

  # GET /hoods
  # GET /hoods.json
  def index
    @hoods = Hood.all
  end

  # GET /hoods/1
  # GET /hoods/1.json
  def show
  end

  # GET /hoods/new
  def new
    @hood = Hood.new
  end

  # GET /hoods/1/edit
  def edit
  end

  # POST /hoods
  # POST /hoods.json
  def create
    @hood = Hood.new(hood_params)

    respond_to do |format|
      if @hood.save
        format.html { redirect_to @hood, notice: 'Hood was successfully created.' }
        format.json { render :show, status: :created, location: @hood }
      else
        format.html { render :new }
        format.json { render json: @hood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hoods/1
  # PATCH/PUT /hoods/1.json
  def update
    respond_to do |format|
      if @hood.update(hood_params)
        format.html { redirect_to @hood, notice: 'Hood was successfully updated.' }
        format.json { render :show, status: :ok, location: @hood }
      else
        format.html { render :edit }
        format.json { render json: @hood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hoods/1
  # DELETE /hoods/1.json
  def destroy
    @hood.destroy
    respond_to do |format|
      format.html { redirect_to hoods_url, notice: 'Hood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hood
      @hood = Hood.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hood_params
      params.require(:hood).permit(:name, :description, :longitude, :latitude, :image)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  skip_before_action :authenticate_user! # , :only => [:index, :show]
  def home
  end

  def about
  end

  def listings
  end

  def hoods
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, :only => [:index, :show]
  # load_and_authorize_resource

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:state, :country, :zip, :listingType, :sqftSize, :brokerage, :image, :address, :price, :city, :area, :bedrooms, :bathrooms, :listingText, :listingExtras, :saleOrLease, :longitude, :latitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/hoods_helper.rb
module HoodsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/hoods/_form.html.erb
<%= form_with(model: hood, local: true) do |form| %>
  <% if hood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hood.errors.count, "error") %> prohibited this hood from being saved:</h2>

      <ul>
      <% hood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :hood_name, class: "form-control", placeholder: "Enter Neighborhood Name", 'aria-describedby': "nameHelp" %>
    <small id="nameHelp" class="form-text text-muted">Example: Yorkville</small>
  </div>


  <div class="form-group">
    <%= form.label :description, "Neighborhood description" %>
    <%= form.text_area :description, id: :hood_description, rows: 3, class: "form-control", placeholder: "Describe The Neighborhood", 'aria-describedby': "descriptionHelp" %>
    <small id="descriptionHelp" class="form-text text-muted">Example: My man slime got this whole shit on lock nigga, him and dutch nigga ask about the team</small>
  </div>


  <div class="form-group">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :hood_latitude, class: "form-control", placeholder: "-79.384293", 'aria-describedby': "longitudeHelp" %>
    <small id="latitudeHelp" class="form-text text-muted">Example: -79.384293</small>

  </div>

  <div class="form-group">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :hood_latitude, class: "form-control", placeholder: "43.653908", 'aria-describedby': "latitudeHelp" %>
    <small id="latitudeHelp" class="form-text text-muted">Example: 43.653908</small>
  </div>

  <%#= form.hidden_field :image, value: hood.cached_image_data %>

  <div class="form-group">
    <%= form.label :image, "Add an image" %>
    <%= form.file_field :image, id: :hood_image, class: "form-control", 'aria-describedby': "fileHelp" %>
    <small id="addressHelp" class="form-text text-muted">Example: Literally any photo of this place at all, even a shitty one.</small>
  </div>



  <div class="actions">
    <%= form.submit 'Submit', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/hoods/edit.html.erb
<h1>Editing Hood</h1>

<%= render 'form', hood: @hood %>

<%= link_to 'Show', @hood %> |
<%= link_to 'Back', hoods_path %>

app/views/hoods/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<% title "Neighborhoods" %>

<% if current_user && current_user.admin_role? %>
  <div class="container placeContainer mb-4">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h6>Yer an admin and you can do shit like this:</h6>
          <%= link_to 'New Hood', new_hood_path %>
          <hr/>
      </div>
    </div>
  </div>
<% end %>

<div class="container">
  <% for hood in @hoods.all.order(:name) %>
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
      <%= link_to(image_tag(hood.image.url, style: 'width: 100%;', class: 'mb-4'), hood) %>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
      <% if current_user && current_user.admin_role? %>
          <%= link_to 'Show', hood %> | <%= link_to 'Edit', edit_hood_path(hood) %> | <%= link_to 'Destroy', hood, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      <h1><%= hood.name %></h1>
      <p><%= hood.description %></p>
    </div>


  </div>
  <% end %>
</div>

app/views/hoods/new.html.erb
<h1>Add A New Neighborhood</h1>
<p>You'll have all your neighborhood related shit here about whats good with it, where its at, and some history or whatever.</p>

<%= render 'form', hood: @hood %>

<%= link_to 'Back', hoods_path %>

app/views/hoods/show.html.erb
<p id="notice"><%= notice %></p>


<% title @hood.name %>

<% if current_user && current_user.admin_role? %>
  <div class="container placeContainer mb-4">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h6>Yer an admin and you can do shit like this:</h6>
        <%= link_to 'Edit ' + @hood.name.to_s, edit_hood_path(@hood) %>
          <hr/>
      </div>
    </div>
  </div>
<% end %>


<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
      <%= image_tag(@hood.image.url, style: 'width: 100%;', class: 'mb-4') %>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
      <h1><%= @hood.name %></h1>
      <p><%= @hood.description %></p>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> -->

    <footer class="mt-4">
     <div class="container">
       <div class="row">

                <div class="col-lg-5 col-md-5 col-sm-4 col-xs-12">
                    <ul class="adress">
                         <span>Contact</span>
                         <li>
                           <p><%= image_tag 'logo-white.png' %></p>
                         </li>
                         <li>
                           <p><b><%= MUSE_CONFIG['brokerage_name'] %></b></p>
                         </li>
                          <li>
                            <p><i><%= MUSE_CONFIG['brokerage_tagline'] %></i></p>
                          </li>


                         <li>
                           <p>
                             <%= MUSE_CONFIG['brokerage_address1'] %><br/>
                             <%= MUSE_CONFIG['brokerage_address2'] %><br/>
                           </p>
                         </li>
                          <li>
                            <p><i class="fa fa-envelope-o fa-1x"></i>broker@fakebrokerage.fake</p>
                          </li>

                          <li>
                            <p><i class="fa fa-phone fa-1x"></i>555-555-5555</p>
                          </li>

                          <li>
                            <p><i class="fa fa-fax fa-1x"></i>555-555-5555</p>
                          </li>
                     </ul>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <ul class="contact">
                         <span>Navigation</span>
                         <li>
                            <a href="/">Home</a>
                          </li>

                          <li>
                            <a href="/places">Listings</a>
                          </li>

                          <li>
                            <a href="/contact">Contact</a>
                         </li>
                         <li>&nbsp;</li>
                         <% if user_signed_in? %>
                           <li>
                             <%= link_to('Edit registration', edit_user_registration_path) %>
                           </li>
                           <li>
                             <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                           </li>
                         <% else %>
                          <li>
                            <%= link_to('Register', new_user_registration_path)  %>
                          </li>
                          <li>
                            <%= link_to('Login', new_user_session_path)  %>
                          </li>

                         <% end %>
                         </li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                   <ul class="social">
                              <span>Social</span>
                               <li>
                                    <a href="#"><i class="fa fa-facebook fa-2x"></i></a>
                               </li>

                               <li>
                                    <a href="#"><i class="fa fa-github fa-2x"></i></a>
                               </li>

                               <li>
                                    <a href="#"><i class="fa fa-linkedin fa-2x"></i></a>
                               </li>

                               <li>
                                    <a href="#"><i class="fa fa-tumblr fa-2x"></i></a>
                               </li>

                               <li>
                                    <a href="#"><i class="fa fa-google-plus fa-2x"></i></a>
                              </li>

                     </ul>
                </div>


           </div>
           <ul class="adress" style="padding-top: 60px;">
             <li><p>Powered by MUSE ESTATE</li>
               <li><p></p></li>
           </ul>

        </div>

    </footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light">
  <a class="navbar-brand" href="/"><%= image_tag('logo.png') %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/places">Listings</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/hoods">Neighborhoods</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/about">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>

      <!-- <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    </ul>
    <div class="my-2 my-lg-0">
    <ul class="navbar-nav mr-auto">

        <% if current_user.nil? %>
          <li class="nav-item">
          	<%= link_to new_user_session_path, class: 'nav-link login-button' do %>Client Sign in<% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <span class="nav-link"><%= current_user.email.split("@").first %></span>
          </li>
          <li class="nav-item">
            <span class="nav-link">|</span>
          </li>
          <li class="nav-item">
          	<%= link_to rails_admin_path, class: 'nav-link login-button' do %>admin<% end %> <!-- app_dashboard_index_path -->
          </li>
          <li class="nav-item">
            <span class="nav-link">|</span>
          </li>
          <li class="nav-item">
            <%= link_to('Logout', destroy_user_session_path, :method => :delete,  class: 'nav-link') %>
          </li>
        <% end %>
      </li>


    </ul>
    </div>

    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search listings" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= MUSE_CONFIG['site_name'] %> &mdash; <%= content_for?(:title) ? yield(:title) : 'This shit is deeper than real estate.' %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">


  </head>

  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= render "/layouts/header" %>

    <main role="main" class="container">

      <%= yield %>

    </main><!-- /.container -->

    <%= render "/layouts/footer" %>

  </body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<% title "Listings" %>

<% if current_user && current_user.admin_role? %>
  <div class="container placeContainer mb-4">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h6>Yer an admin and you can do shit like this:</h6>
          <%= link_to 'New Place', new_place_path %>
          <hr/>
      </div>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h1>Listings</h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% for place in @places.all.order(:created_at) %>
      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 placeWidget">
        <%= render "/shared/placeWidget", place: place %>
    </div>
    <% end %>
  </div>
</div>

app/views/places/new.html.erb
<h1>Add A New Place</h1>
<p>A quick rundown on this page and how this functions. Right now we are entering this shit in by hand because we're a fictional
  brokerage that doesn't actually exist. If we were actually a brokerage or perhaps an agent from a brokerage, we could use a <%= link_to 'Ruby RETS', 'https://github.com/estately/rets' %> plugin and fish the listings from a rets server that most real estate boards provide, and populate this shit with a RETS feed. Just saying...</p>

<%= render 'form', place: @place %>
<br/>
<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<% title @place.title_address   %>

<% if current_user && current_user.admin_role? %>
  <div class="container placeContainer mb-4">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h6>Yer an admin and you can do shit like this:</h6>
          <%= link_to 'Edit this place', edit_place_path(@place) %>
          <hr/>
      </div>
    </div>
  </div>
<% end %>



<style media="screen">
  img {
    width: 100%;
  }
</style>
<!-- <p id="notice"><%= notice %></p> -->

<div class="container placeContainer">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
      <h1><%= @place.address %>, <%= @place.city %></h1>
      For <%= @place.sale_or_lease?.capitalize %><br/>
      <%= @place.city %>, <%= @place.state %> <%= @place.zip %> &mdash; <%= @place.area %><br/>
      1000-2000 sq ft</br>
      beds: <%= @place.bedrooms %> / baths: <%= @place.bathrooms %></p>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 text-right">
      <h1><span class="price"><%= number_to_currency(@place.price) %></span></h1>
    </div>

  </div>
  <div class="row mb-3">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 homePlace">
      <%= image_tag(@place.image.url) %>
    </div>
  </div>

  <!--<div class="row mb-4">-->
    <!--<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">-->
      <!--<h3>Sexy Details</h3>-->

    <!--</div>-->
    <!--<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">-->
      <!--&nbsp;-->
    <!--</div>-->
  <!--</div>-->

  <div class="row mb-4">
    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
      <h3>Listing Text</h3>
      <p><%= @place.listingText %></p>
      <h3>Extras</h3>
      <p><%= @place.listingExtras %></p>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 agentBox">
      <h3 class="mb-2">Socials</h3>
      <a class="btn btn-social-icon btn-twitter">
        <span class="fa fa-twitter" style="color: white;"></span>
      </a>

      <a class="btn btn-social-icon btn-facebook">
        <span class="fa fa-facebook" style="color: white;"></span>
      </a>

      <a class="btn btn-social-icon btn-google">
        <span class="fa fa-google" style="color: white;"></span>
      </a>


      <hr/>
      <p><%= image_tag('agent.jpg') %></p>
      <h3>Fakey McFakerson</h3>
      <p>Broker</p>
      <p><i>"I made my bones when you were going out with cheerleaders!"</i><br/></p>
      <p><i class="fa fa-phone fa-1x"></i>416-555-5555</a></p>
      <p><i class="fa fa-globe fa-1x"></i>fakebrokerage.fake</p>
      <p class="mb-3"><i class="fa fa-envelope-o fa-1x"></i>broker@fakebrokerage.fake</p>
      <hr/>
      <p><%= image_tag('logo.png') %></p>
      <p><b>Fake Brokerage, INC</b></p>
      <p>123 Fake Street</p>
      <p>Toronto, Ontario M4M M4MM</p>
      <p><i class="fa fa-phone fa-1x"></i>416-555-5555</a></p>
      <p><i class="fa fa-fax fa-1x"></i>416-555-5555</a></p>
    </div>


    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
    </div>

  </div>

</div>


<%= link_to 'Back', places_path %>

app/views/shared/_placeWidget.html.erb
<% if current_user && current_user.admin_role == true %>
  <%= link_to 'Show', place %> | <%= link_to 'Edit', edit_place_path(place) %> | <%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %>
  <br/>
<% end %>
<%= link_to(image_tag(place.image.url), place) %>
<%= number_to_currency(place.price, precision: 0)%>
<br/>
<%= place.address %>, <%= place.area %>
<br/>
<i class="fa fa-bed fa-1x"></i><%= place.bedrooms %> <i class="fa fa-bath" aria-hidden="true"></i><%= place.bathrooms %><br/></b><br/>